<div class="row row-offcanvas row-offcanvas-left">
    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
    	 <?php echo $this->adminMenu("admin-index");?>
    </div>
    <div class="col-xs-12 col-sm-9">
    	<div class="panel panel-default">
    		<div class="panel-heading">
    			<i class="fa fa-gavel" aria-hidden="true"></i>
    			<?php echo $this->translate("Home Page Auctions"); ?>
    			<span class="pull-right">
    				<?php echo $this->createButton("home-auction-admin-create"); ?>
    			</span>
    		</div>
    		<?php if($this->paginator->count() == 0): ?>
        	<div class="alert alert-info">
        		<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('No auctions'); ?>
        	</div>
        	<?php else: ?>
        	<div class="table-responsive">
				<table class="table table-hover table-striped table-condensed">
					<thead>
						<tr>
							<th><?php echo $this->translate("Image"); ?></th>
							<th><?php echo $this->translate("Title"); ?></th>
							<th><?php echo $this->translate("User"); ?></th>
							<th><?php echo $this->translate("Price"); ?></th>
							<th><?php echo $this->translate("Ends"); ?></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->paginator as $entity): ?>
						<tr>
							<td><img src="<?php echo $entity->getAuctionEntity()->getPictureEntity()->getPictureUrl(); ?>" class="img-responsive img-rounded" /></td>
							<td><a href="" title="<?php echo $this->translate("View Auction"); ?>"><?php echo $entity->getAuctionEntity()->getAuctionHeading(); ?></a></td>
							<td></td>
							<td nowrap><?php echo $this->currencyFormat($entity->getAuctionEntity()->getAuctionCurrentBidValue(), "USD", "en_US"); ?></td>
							<td nowrap><?php echo date("m/d/Y h:i a", $entity->getAuctionEntity()->getAuctionEndUnixtime()); ?></td>
							<td>
								<?php echo $this->deleteButton("home-auction-admin-delete", array("id" => $entity->getHomePageAuctionId()));?>
							</td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
        	<?php endif; ?>
        	<div class="row">
				<div class="col-xs-12 text-center small">
					<?php echo $this->Paginator(
    					$this->itemCountPerPage, 
    					$this->itemCount, 
    					$this->pageCount, 
                        $this->page, 
                        $this->routeParams,
                        $this->queryParams);
                    ?>
				</div>
			</div>
        </div>
    </div>
</div>